/*
 * generated by Xtext 2.20.0
 */
package org.eclipse.emf.eson.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.commands.IExecutableCommandService;
import org.eclipse.xtext.ide.server.hover.HoverService;
import org.xtext.example.mydsl.ide.contentassist.MyDslIdeContentProposalProvider;

/**
 * Use this class to register ide components.
 */
public class EFactoryIdeModule extends AbstractEFactoryIdeModule {
	
	public Class<? extends HoverService> bindHoverService() {
		return EclipseLikeHoverService.class;
	}
	
	public Class<? extends IExecutableCommandService> bindIExecutableCommandService() {
		return CommandService.class;
	}
	
	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return MyDslCodeActionService.class;
	}
	
	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return MyDslIdeContentProposalProvider.class;
	}
}
