/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.emf.eson;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EFactoryStandaloneSetup extends EFactoryStandaloneSetupGenerated {

	public static void doSetup() {
		new EFactoryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
